<?php
// auto-generated by sfPropelCrud
// date: 2008/04/02 13:21:49
?>
<h1><?php echo __('History actions list') ?></h1>

<table>
<thead>
<tr>
  <th><?php echo __('Description') ?></th>
  <th><?php echo __('Actions') ?></th>
</tr>
</thead>
<tbody>
<?php foreach ($history_actions as $history_action): ?>
<tr>
      <td style="padding-right: 10px;"><?php echo ($history_action->getDescription()? $history_action->getDescription() : $history_action->getName()) ?></td>
      <td><?php echo link_to(__('Edit'), 'admin/historyActionEdit?id='.$history_action->getId()) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
