<?php
// auto-generated by sfPropelCrud
// date: 2008/04/02 13:21:49

reaktor::setReaktorTitle(__('History action editor')); 
use_helper('Object');
?>

<?php echo form_tag('@historyactionupdate') ?>
  <?php echo object_input_hidden_tag($history_action, 'getId') ?>
  <?php echo object_input_hidden_tag($history_action, 'getName') ?>
  
  <h2><?php echo __('Translating %item_name%', array('%item_name%' => $history_action->getName())); ?></h2>
  <table>
    <tbody>
      <tr>
        <th style="padding-right: 10px;"><?php echo __('Untranslated text') ?>:</th>
        <td><?php echo $history_action->getName(); ?></td>
      </tr>
      <tr>
        <th><?php echo __("Translated (%language%) text", array("%language%" => $sf_user->getCultureName()));?></th>
        <td><?php echo object_input_tag($history_action, 'getDescription', array (
        'disabled' => false,
      )) ?></td>
      </tr>
    </tbody>
  </table>
  <hr />
  <?php echo submit_tag(__('Save')) ?>
&nbsp;<?php echo link_to(__('Cancel'), '@historyactions') ?>
</form>
