<?php
// auto-generated by sfPropelCrud
// date: 2008/04/02 13:21:49
?>
<h1><?php echo __('Permission description list') ?></h1>

<table>
  <thead>
  <tr>
    <th><?php echo __('Permission description') ?></th>
    <th><?php echo __('Identifier') ?></th>
    <th><?php echo __('Actions') ?></th>
  </tr>
  </thead>
  <tbody>
  <?php foreach ($permissions as $permission): ?>
  	<tr>
        <td style="padding-right: 10px;"><?php echo $permission->getName() ?></td>
        <td><?php echo link_to(__('Edit'), '@sfguardpermissiondescriptionedit?id='.$permission->getId()) ?></td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
