<?php
// auto-generated by sfPropelCrud
// date: 2008/04/02 13:21:49
?>
<?php use_helper('Object') ?>

<?php echo form_tag('@sfguardpermissiondescriptionupdate') ?>

<?php echo object_input_hidden_tag($edit_permission, 'getId') ?>
<?php echo object_input_hidden_tag($edit_permission, 'getName') ?>

<h2><?php echo __('Translating %item_name%', array('%item_name%' => $edit_permission->getName())); ?></h2>
<table>
<tbody>
<tr>
  <th style="padding-right: 10px;"><?php echo __('Permission identifier') ?>:</th>
  <td><?php echo $edit_permission->getName(); ?></td>
</tr>
<tr>
  <th><?php echo __('Translated description') ?></th>
  <td><?php echo object_input_tag($edit_permission, 'getDescription', array (
  'disabled' => false,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag(__('Save')) ?>
&nbsp;<?php echo link_to(__('Cancel'), '@sfguardpermissiondescriptionlist') ?>
<?php echo '</form>'; ?>