<?php
// auto-generated by sfPropelCrud
// date: 2008/04/02 13:21:49
?>
<h1><?php echo __('Rejectiontypes') ?></h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>

</tr>
</thead>
<tbody>
<?php foreach ($rejection_types as $rejection_type): ?>
<tr>
    <td><?php echo $rejection_type->getId() ?></td>
      <td><?php echo link_to($rejection_type->getName(), '@rejectiontypeshow?id='.$rejection_type->getId()) ?></td>

  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', '@rejectiontypecreate') ?>
