<?php
// auto-generated by sfPropelCrud
// date: 2008/04/02 13:21:49
?>
<?php use_helper('Object') ?>

<?php echo form_tag('@rejectiontypeupdate') ?>

<?php echo object_input_hidden_tag($rejection_type, 'getId') ?>

<h2><?php echo __('Translating %item_name%', array('%item_name%' => $rejection_type->getName())); ?></h2>
<table>
<tbody>
<tr>
  <th>Name*:</th>
  <td><?php echo object_input_tag($rejection_type, 'getName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Description*:</th>
  <td><?php echo object_textarea_tag($rejection_type, 'getDescription', array (
  'disabled' => false,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($rejection_type->getId()): ?>
  &nbsp;<?php echo link_to('delete', '@rejectiontypedelete?id='.$rejection_type->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', '@rejectiontypeshow?id='.$rejection_type->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', '@rejectiontypes') ?>
<?php endif; ?>
<?php echo '</form>'; ?>