<?php
// auto-generated by sfPropelCrud
// date: 2008/04/02 13:21:49
?>
<table>
<tbody>
<tr>
<th><?php echo __("Id:") ?> </th>
<td><?php echo $rejection_type->getId() ?></td>
</tr>
<tr>
<th><?php echo __("Name:") ?> </th>
<td><?php echo $rejection_type->getName() ?></td>
</tr>
<tr>
<th><?php echo __("Description:") ?> </th>
<td><?php echo $rejection_type->getDescription() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to(__('edit'), 'admin/rejectionTypeEdit?id='.$rejection_type->getId()) ?>
&nbsp;<?php echo link_to(__('list'), 'admin/rejectionTypeList') ?>
