<?php
// auto-generated by sfPropelCrud
// date: 2008/04/02 13:21:49
?>
<h1><?php echo __('subReaktor name list') ?></h1>

<table>
  <thead>
  <tr>
    <th><?php echo __('subReaktor name') ?></th>
    <th><?php echo __('Reference') ?></th>
    <th><?php echo __('Actions') ?></th>
  </tr>
  </thead>
  <tbody>
  <?php foreach ($subreaktor_names as $subreaktor_name): ?>
  	<tr>
        <td style="padding-right: 10px;"><?php echo $subreaktor_name->getName() ?></td>
        <td style="padding-right: 10px;"><?php echo $subreaktor_name->getReference() ?></td>
        <td><?php echo link_to(__('Edit'), '@subreaktornameedit?id='.$subreaktor_name->getId()) ?></td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
