<?php
/**
 * Started out as a file auto-generated by sfPropelCrud
 * date: 2008/02/07 11:25:21
 *   
 * PHP version 5
 *
 * @author    juneih <juneih@linpro.no>
 * @copyright 2008 Linpro
 * @license   http://www.gnu.org/copyleft/lesser.html  LGPL License 2.1
 *
 */

use_helper('Validation', 'Object', 'm2mCheckBox', 'Javascript', 'wai');
reaktor::setReaktorTitle(__('Edit profile of %username%', array("%username%" => $sf_guard_user->getUsername()))); 

?>
<?php if ($sf_request->hasErrors()): ?>
  <div class="form_error">
	  <p><b><?php echo __('The changes were not saved.'); ?><br /></b>
	  <?php echo __('Please correct the errors below and try again.'); ?></p>
  </div>
<?php elseif ($issaved): ?>
  <p><b><?php echo __('The changes were saved'); ?></b></p>
<?php endif; ?>
<h1> 
  <?php echo __('Edit profile of %username%', array("%username%" => $sf_guard_user->getUsername())); ?>
</h1>
<?php if ($sf_guard_user->getNeedProfileCheck()): ?>
	<div class="message warning_box" style="width:590px;">
  <?php echo __("<h2>Welcome back to Reaktor!</h2><br /> We have detected that your profile may need updating, please check the information below.
		             <br />Even if the information is correct, please click 'save changes' to clear this message."); ?>
	</div>
	<br />
<?php endif; ?>

<?php echo reaktor_form_tag('@updateprofile', 'multipart=true'); ?>
  
  <div class="profile_left">  

    <?php include_partial('userProfile', array(
      'sf_guard_user'=>$sf_guard_user, 
      'profile'=>'edit',
      'residence_array' => $residence_array 
    )); ?>
       <br />
    <?php echo wai_label_for('catalogue', __('Preferred language')); ?> <br />
    <?php echo form_error('catalogue'); ?>
    <?php echo select_tag('catalogue', options_for_select($catalogue,$cat_default), array(
     'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'",
     'onfocus' => "$('information_msg').innerHTML='".__('**help-text for language**')."'"
  )); ?>
    <br />    
    <?php echo wai_label_for('name', __('Full name')); ?>
    <?php echo form_error('name'); ?>
    <?php echo object_input_tag($sf_guard_user, 'getName',  array (
      'size'    => 80,
      'onfocus' => "$('information_msg').innerHTML='".__('**help-text for fullname**')."'",
      'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'",
    )); ?>
  
    <div class='extra_padding'>
      <?php echo object_checkbox_tag($sf_guard_user, 'getNamePrivate', array( 
        'onfocus' => "$('information_msg').innerHTML='".__('**help-text for hidden fullname**')."'",
        'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'",
      )); ?>
      <?php echo wai_label_for('name_private', __('Keep my full name hidden from other users'), array(
        'class'=>'normal_text'        
      )); ?> 
    </div>
    <div class='extra_padding'>
        <?php echo object_checkbox_tag($sf_guard_user, 'getShowLoginStatus', array(
          'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'",
          'onfocus' => "$('information_msg').innerHTML='".__('**help-text for show_login_status**')."'"
        )); ?>
        <?php echo wai_label_for('show_login_status', __('Show my login status to other users'), array(
          'class'=>'normal_text',      
        )); ?> 
    </div>

      
    <?php
    /* 
    echo wai_label_for('description', __('Description')); 
    echo form_error('description'); 
    echo object_textarea_tag($sf_guard_user, 'getDescription', array (
    'disabled' => false, 
    'onfocus' => "$('information_msg').innerHTML='".__('**help-text for description**')."'",
    'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'"
    ))
    */
    ?>

    <div class='contact_info_row'>  
      <dl class='contact_info'>
        <?php echo form_error('msn'); ?>
        <dt><?php echo wai_label_for('msn', __('MSN')); ?></dt>
        <dd><?php echo object_input_tag($sf_guard_user, 'getMsn', array(
          'size' => 80, 
          'class'=>'short',
          'onfocus' => "$('information_msg').innerHTML='".__('**help-text for msn**')."'",
          'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'"
         ))?></dd>
        <?php echo form_error('icq'); ?>
        <dt><?php echo wai_label_for('icq', __('ICQ')); ?></dt>
        <dd><?php echo object_input_tag($sf_guard_user,'getIcq', array(
          'size' => 15,
          'class'=>'short',
          'onfocus' => "$('information_msg').innerHTML='".__('**help-text for icq**')."'",
          'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'",       
        )); ?></dd>
        <?php echo form_error('homepage'); ?>
        <dt><?php echo wai_label_for('homepage', __('Homepage')); ?></dt>
        <dd><?php echo object_input_tag($sf_guard_user, 'getHomepage',  array(
          'size' => 80,          
          'class'=>'short',
          'onfocus' => "$('information_msg').innerHTML='".__('**help-text for homepage**')."'",
          'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'",
        )); ?></dd>
        <?php echo form_error('phone'); ?>
        <dt><?php echo wai_label_for('phone', __('Phone')); ?></dt>
        <dd><?php echo object_input_tag($sf_guard_user,  'getPhone', array(
          'size' => 32,
          'class'=>'short', 
          'onfocus' => "$('information_msg').innerHTML='".__('**help-text for phone**')."'",
          'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'",
        )); ?></dd>      
      </dl>
      <div style="clear: both;"></div>
    </div>
    <div class='extra_padding'>
      <?php echo object_checkbox_tag($sf_guard_user, 'getOptIn', array( 
        'onfocus' => "$('information_msg').innerHTML='".__('**help-text for receiving admin email**')."'",
        'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'",
      )); ?>
      <?php echo wai_label_for('optin', __('Yes, I agree to receive e-mails from Reaktor regarding events, competitions, seminars etc '), array(
        'class'=>'normal_text'        
      )); ?> 
    </div>
    <div class='right_buttons'>
      <?php echo submit_tag(__('Save changes')); ?>
      <?php echo reaktor_button_to(__('Cancel'), '@home'); ?>
    </div>
  
  </div>
  
  <div class='profile_right'>

    <h2 id='information_msg'>
        <?php echo __('**help-text when no field is selected**'); ?>
    </h2>



  <div  style = "border: 1px solid silver;width: 295px;">
    <dl>
      <dt> 
        <?php echo wai_label_for('avatar', __('Avatar')); ?>
      </dt>  
      <dd>
    <?php
        $avatar_path = !is_null($sf_guard_user->getAvatar()) ? $sf_guard_user->getAvatar() : "default.gif"; 

echo '<table><tr>';
echo '<td  id = "avatar_image">'.image_tag(sfConfig::get("app_profile_avatar_url").$avatar_path).'</td>';
echo "<td><input type=\"button\" value=\"".__("Set new image")."\" onclick=\"document.getElementById('avatar_edit').style.display='block'\"></td>";
echo '</tr></table>';

  ?>

      </dd>
    </dl>
    </div>





  
    <div id='interests_box'>
      <em><strong><?php echo __('Interests'); ?></strong></em>
<?php echo form_error('interests'); ?>
      <?php foreach(items_for_select(SubreaktorPeer::getSubReaktors(false,true),'getId','__toString') as $key=>$value)://, $interests)?>
      
        <div class='profile_interest'>        
            <?php  echo checkbox_tag($value, $key, array_key_exists($key,$interests)?true:false, array(
            'onfocus' => "$('information_msg').innerHTML='".__('**help-text for interest**')."'",
            'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'",
            )); ?>
            <?php  echo ucfirst(__($value)).' ' ?>
        </div>    
     <?php endforeach ?>
     <em><strong><?php echo __("Member of LocalReaktor"); ?></strong></em>
      <?php foreach(items_for_select(SubreaktorPeer::getLokalReaktors(false,true),'getId','__toString') as $key=>$value)://, $interests)?>
      
        <div class='profile_interest'>        
            <?php  echo checkbox_tag($value, $key, array_key_exists($key,$interests)?true:false, array(
            'onfocus' => "$('information_msg').innerHTML='".__('**help-text for interest**')."'",
            'onblur'  => "$('information_msg').innerHTML='".__('**help-text when no field is selected**')."'",
            )); ?>
            <?php  echo ucfirst(__($value)).' ' ?>
        </div>    
     <?php endforeach ?>
    </div>
  
  </div>

  
  
</form>
<?php if (count($sf_guard_user->getEditorialTeams()) > 0): ?>
  <div class="edit_user_editorialteam">
	  <h4><?php echo __('New artwork notification'); ?></h4>
	  <?php echo __('Select how you want to be notified of new artwork'); ?>
    <?php include_partial('admin/userEditorialTeam', array('user' => $sf_guard_user)); ?>
  </div>
<?php endif; ?>      
	


<?php echo javascript_tag("

    function completeCallback_custom(response) 
    {
    // make something useful after (onComplete)
    $('image_block').innerHTML = response;
    $('avatar_image').innerHTML = response;
     
    $('newimage').value = '';
    document.getElementById('avatar_edit').style.display='none';
                        }

") ?>




    <div id="avatar_edit" class = "clearboth"  style="display: none; left: 420px; top:100px;">
    <dl>
      <dt> 
        <?php echo wai_label_for('avatar', __('Avatar')); ?>
      </dt>  
      <dd>
        <?php
        $avatar_path = !is_null($sf_guard_user->getAvatar()) ? $sf_guard_user->getAvatar() : "default.gif"; 
        include_partial("upload/inlineUpload", array(
        "avatarUserId" => $sf_guard_user->getId(), 
     'completeCallback' => 'completeCallback_custom', 
     'extra_button' => "<input type=\"button\" value=\"".__("Cancel")."\" onclick=\"document.getElementById('avatar_edit').style.display='none';$('newimage').value = '';\">", 

        "imgTag" => image_tag(sfConfig::get("app_profile_avatar_url").$avatar_path, array(

          'class' => 'floatleft',
          'size'  => '48x48',
        )))); 
        ?>
      </dd>
    </dl>
    </div>





<?php

echo javascript_tag('window.setTimeout("clearPasswordBoxes();", 100)');

?>