<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/01 14:47:17
sfConfig::add(array(
  'sf_i18n_default_culture' => 'no',
  'sf_i18n_source' => 'MySQL',
  'sf_i18n_debug' => true,
  'sf_i18n_cache' => false,
  'sf_i18n_untranslated_prefix' => '',
  'sf_i18n_untranslated_suffix' => '',
  'sf_i18n_database' => 'mysql://reaktor_user:cT0PHPCm@localhost/reaktor',
));
