propel:
  _attributes:      { package: lib.model }
  
  lokalreaktor_artwork:
    id:
    subreaktor_id:    { type: integer, required: true, foreignTable: subreaktor, foreignReference: id }
    artwork_id:       { type: integer, required: true, foreignTable: reaktor_artwork, foreignReference: id }

  lokalreaktor_residence :
    id:
    created_at:
    subreaktor_id:    { type: integer, required: true, foreignTable: subreaktor, foreignReference: id }
    residence_id:     { type: integer, required: true, foreignTable: residence, foreignReference: id }
    
 