propel:
  _attributes:        { package: lib.model }
  
  user_interest:
    user_id:          {type: integer, primaryKey: true, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade}
    subreaktor_id:    {type: integer, primaryKey: true, required: true, foreignTable: subreaktor, foreignReference: id, onDelete: cascade}
